Update eb_builder/develop eb wrapper. Clean up nvidia/cuda handling (should later be dropped in favor of using singularity -nv) Add possibility to use container where /bin/bash is /bin/sh (ubuntu has /bin/dash as /bin/sh) Also using a container where OS python setuptools is available (required for ReFrame installation)

diff --git a/eb_builder/develop/bin/eb b/eb_builder/develop/bin/eb
--- a/eb_builder/develop/bin/eb
+++ b/eb_builder/develop/bin/eb
@@ -1,10 +1,5 @@
 #!/bin/bash
 
-if [ -z "$EBUSER" ]; then
-    echo "ERROR: Must set EBUSER before using eb_builder/develop"
-    exit 1
-fi
-
 c=`echo $PWD | cut -d/ -f1,2`
 if [ "$c" = "/hpc2n" ]; then
     echo "Having /hpc2n/* as working dir when starting the singularity container will cause trouble due to bind mounts"
@@ -12,25 +7,32 @@ if [ "$c" = "/hpc2n" ]; then
     exit 1
 fi
 
-# Find latest installed version of nvidia-xxx if any
-# Needed for the NVML libraries, later resolving is done through /etc/ld.so.conf
-d=`find /usr/lib -maxdepth 1 -name nvidia-\* | grep -v 'nvidia-.*-'`
-if [ -n "$d" ]; then
-    l=`readlink -f /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf`
-    nvidia="-B $d -B $l:/etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf -B /etc/ld.so.cache"
-    l=`readlink -f /usr/lib/x86_64-linux-gnu/libcuda.so.1`
-    cuda="-B /usr/lib/x86_64-linux-gnu/libcuda.so.1 -B /usr/lib/x86_64-linux-gnu/libcuda.so -B $l"
-else
-    nvidia=""
-    cuda=""
+# Find nvidia libs
+nvidia=$(find /usr/lib/x86_64-linux-gnu -maxdepth 1 -name libnvidia-\* | sed 's/^/-B /')
+
+# Find cuda libs
+cuda=$(find /usr/lib/x86_64-linux-gnu -maxdepth 1 -name libcuda\* | sed 's/^/-B /')
+
+# Find Slurm related things
+munge=$(find /run -maxdepth 1 -name munge | sed 's/^/-B /')
+etc_slurm=$(find /etc -maxdepth 1 -name slurm | sed 's/^/-B /')
+lap_slurm=$(find /lap -maxdepth 1 -name slurm | sed 's/^/-B /')
+
+if [ -z "$EBUSER" ]; then
+    echo "ERROR: Must set EBUSER before using eb_builder/develop"
+    exit 1
 fi
 
-# Bind mounts:
-#  /hpc2n: top level prefix with link to the correct architecture
-#  /run/munge: Munge socket
-#  /etc/slurm: Slurm configs
-#  /lap/slurm: Slurm installation(s)
-#  /usr/local/bin: is available in $PATH and contains links to srun etc. For some reason MPI didn't work well without this, both Impi and OpenMPI had problems without it)
-#  $nvidia and $cuda: See above, runtime driver libraries
+if [ -n "$EB_BASH_AS_SH" ]; then
+    bash_as_sh="-bash_as_sh"
+else
+    bash_as_sh=""
+fi
 
-singularity run -B /hpc2n -B /run/munge -B /etc/slurm -B /lap/slurm -B /usr/local/bin $nvidia $cuda -B /import/ebswbuild/master:/cvmfs/ebsw.hpc2n.umu.se /pfs/nobackup/data/containers/easybuild/xenial-eb-base-autobuild.simg "$@"
+if [ -n "$EB_SETUPTOOLS" ]; then
+    system_setuptools="-system_setuptools"
+else
+    system_setuptools=""
+fi
+
+singularity run -B /hpc2n $munge $etc_slurm $lap_slurm -B /usr/local/bin $nvidia $cuda -B /import/ebswbuild/master:/cvmfs/ebsw.hpc2n.umu.se /pfs/data/containers/easybuild/focal-eb-base-autobuild$bash_as_sh$system_setuptools.simg "$@"
